DROP TABLE IF EXISTS roles;
DROP SEQUENCE IF EXISTS roles_role_id_seq;
CREATE TABLE roles(role_id SERIAL PRIMARY KEY, role VARCHAR(20) NOT NULL);

INSERT INTO roles (role) VALUES ('ADMIN_ROLE');
INSERT INTO roles (role) VALUES ('USER_ROLE');
